document.write('<div class="th-admin-sidebar">');
document.write('    <div class="th-admin-brand-logo py-3">');
document.write('        <i class="fa-regular fa-house"></i>');
document.write('        <p class="mb-0">BRIXSAR</p>');
document.write('    </div>');
document.write('    <ul class="th-admin-menu ps-3 pe-2 pt-4 pb-5">');
document.write('        <li class="th-sidebar-menu">');
document.write('            <a href="./index.html" class="th-meunu-link">');
document.write('                <i class="fa-regular fa-cube"></i>');
document.write('                <span>Dashboard</span>');
document.write('            </a>');
document.write('        </li>');
document.write('        <div class="menu-block">');
document.write('            <h5>Property Managment</h5>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="#" class="th-meunu-link submenu-btn">');
document.write('                    <i class="fa-light fa-cubes"></i>');
document.write('                    <span>Sale</span>');
document.write('                    <div class="arrow-btn">');
document.write('                        <i class="fa-solid fa-chevron-down"></i>');
document.write('                    </div>');
document.write('                </a>');
document.write('                <ul class="submenu-dropdown sidebar-submenu">');
document.write('                    <li class="th-sidebar-menu">');
document.write('                    <a href="./add-property.html" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Add Property</span>');
document.write('                    </a>');
document.write('                    </li>');
document.write('                    <li class="th-sidebar-menu">');
document.write('                        <a href="./property-listing.html" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Property Listing</span>');
document.write('                        </a>');
document.write('                    </li>');
document.write('                    <li class="th-sidebar-menu">');
document.write('                        <a href="./sale-propery-enquiry.html" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Property Enquiry</span>');
document.write('                        </a>');
document.write('                    </li>');
document.write('                </ul>  ');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="#" class="th-meunu-link submenu-btn">');
document.write('                    <i class="fa-sharp fa-light fa-rectangles-mixed"></i>');
document.write('                    <span>Rental</span>');
document.write('                    <div class="arrow-btn">');
document.write('                        <i class="fa-solid fa-chevron-down"></i>');
document.write('                    </div>');
document.write('                </a>');
document.write('                <ul class="submenu-dropdown sidebar-submenu">');
document.write('                    <li class="th-sidebar-menu">');
document.write('                    <a href="#" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Add Property</span>');
document.write('                    </a>');
document.write('                    </li>');
document.write('                    <li class="th-sidebar-menu">');
document.write('                        <a href="#" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Property Listing</span>');
document.write('                        </a>');
document.write('                    </li>');
document.write('                    <li class="th-sidebar-menu">');
document.write('                        <a href="#" class="th-meunu-link">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Property Detail</span>');
document.write('                        </a>');
document.write('                    </li>');
document.write('                </ul> ');
document.write('            </li>                           ');
document.write('        </div>');
document.write('        <div class="menu-block">');
document.write('            <h5>Profile</h5>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-sharp fa-light fa-user"></i>');
document.write('                    <span>Users</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-light fa-magnifying-glass"></i>');
document.write('                    <span>Enquiry</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-brands fa-leanpub"></i>');
document.write('                    <span>Forms</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-regular fa-calendar"></i>');
document.write('                    <span>Contact</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="./component.html" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-chalkboard"></i>');
document.write('                    <span>Components</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="#" class="th-meunu-link submenu-btn">');
document.write('                    <i class="fa-light fa-cloud"></i>');
document.write('                    <span>Level 3 dropdown</span>');
document.write('                    <div class="arrow-btn">');
document.write('                        <i class="fa-solid fa-chevron-down"></i>');
document.write('                    </div>');
document.write('                </a>');
document.write('                <ul class="submenu-dropdown sidebar-submenu">');
document.write('                    <li class="th-sidebar-menu">');
document.write('                    <a href="#" class="th-meunu-link submenu-level-2-btn">');
document.write('                        <i class="fa-regular fa-circle"></i>');
document.write('                        <span>Pages</span>');
document.write('                        <div class="arrow-btn">');
document.write('                        <i class="fa-solid fa-chevron-down"></i>');
document.write('                        </div>');
document.write('                    </a>');
document.write('                    <ul class="submenu-dropdown sidebar-submenu-level-2">');
document.write('                        <li>');
document.write('                        <a href="#" class="th-meunu-link submenu-level-3-btn">');
document.write('                            <i class="fa-regular fa-circle"></i>');
document.write('                            <span>Page 1</span>');
document.write('                            <div class="arrow-btn">');
document.write('                            <i class="fa-solid fa-chevron-down"></i>');
document.write('                            </div>');
document.write('                        </a>');
document.write('                        <ul class="submenu-dropdown sidebar-submenu-level-3">');
document.write('                            <li>');
document.write('                            <a href="#" class="th-meunu-link">');
document.write('                                <i class="fa-regular fa-circle"></i>');
document.write('                                <span>Page 1.1</span>');
document.write('                            </a>');
document.write('                            </li>');
document.write('                        </ul>');
document.write('                        </li>');
document.write('                    </ul>');
document.write('                    </li>');
document.write('                </ul>  ');
document.write('            </li>');
document.write('        </div>');
document.write('        <div class="menu-block">');
document.write('            <h5>Accounts</h5>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-money-bill-1"></i>');
document.write('                    <span>Pricing</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-table-cells"></i>');
document.write('                    <span>Tables</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-fire"></i>');
document.write('                    <span>Modals</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-database"></i>');
document.write('                    <span>Data</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-house-chimney"></i>');
document.write('                    <span>Data</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-house-chimney"></i>');
document.write('                    <span>Data</span>');
document.write('                </a>');
document.write('            </li>');
document.write('            <li class="th-sidebar-menu">');
document.write('                <a href="" class="th-meunu-link">');
document.write('                    <i class="fa-solid fa-house-chimney"></i>');
document.write('                    <span>Data</span>');
document.write('                </a>');
document.write('            </li>');
document.write('        </div>');
document.write('    </ul>');
document.write('</div>');